name: sentiment-mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - scikit-learn
  - dvc
  - mlflow
  - pytest 
  - flake8
  - pip:
    - ruff
    - google-api-python-client
    - python-dotenv
    - emoji
    - sentencepiece
    - transformers
    - tiktoken

    - torch
    - torchvision
    - torchaudio