name: mlops-sentiment-youtube
channels:
  - conda-forge
dependencies:
  # --- Python de base ---
  - python=3.10

  # --- Collecte et manipulation de données ---
  - pandas
  - google-api-python-client
  - google-auth-httplib2 # Dépendance pour l'API Google
  
  # --- Machine Learning ---
  - scikit-learn
  - numpy
  
  # --- MLOps ---
  - mlflow
  - dvc
  
  # --- Développement et expérimentation ---
  - jupyterlab
  - notebook
  - matplotlib # Pour les visualisations
  - seaborn    # Pour de plus belles visualisations
  
  # --- Installation via pip si nécessaire ---
  # - pip:
  #  - package-non-dispo-sur-conda