name: CI - Validation de la Pipeline ML

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate-pipeline:
    runs-on: ubuntu-latest

    # Cela garantit que chaque étape "run" utilise un shell
    # qui comprend l'activation de l'environnement Conda.
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Étape 1: Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2: Mettre en place Conda et créer l'environnement
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: sentiment-mlops
          environment-file: environment.yml
          python-version: "3.10"

      # Étape 3: Linter le code avec Flake8
      - name: Lint code with Ruff
        run: |
          ruff check .
          ruff format --check .

      # Étape 4: Lancer les tests unitaires avec Pytest
      - name: Run unit tests
        run: |
          pytest

      # Étape 5: Lancer la pipeline DVC complète
      - name: Run DVC pipeline from scratch
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          echo "YOUTUBE_API_KEY=${YOUTUBE_API_KEY}" > .env
          dvc repro